{% set version = "4.17.1" %}

package:
  name: selenium
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
    sha256: 8203707502f8200c1882a49b9584b2d84d4be5152f3a418cc731c7cb5e813843
  - fn: LICENSE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/LICENSE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/LICENSE
    sha256: de658a7d3761e92b471e2f630ea99eeb3389b27820809b1e4853baabd5fbadb7
  - fn: NOTICE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/NOTICE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/NOTICE
    sha256: 2a3429f61e1ad70d33a6fa517cb46ec183c0b0fbcce34a2183d4c56bea3c874e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - certifi >=2021.10.8
    - python >=3.8
    - selenium-manager {{ version.split('.')[:2] | join('.') }}.*
    - trio >=0.17,<1.dev0
    - trio-websocket >=0.9,<1.dev0
    - urllib3 >=1.26,<3
test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check
    - python -c "from selenium.webdriver.common.selenium_manager import SeleniumManager; assert SeleniumManager.get_binary().exists()"

about:
  home: https://www.selenium.dev
  license_file:
    - LICENSE-selenium-{{ version }}
    - NOTICE-selenium-{{ version }}
  license: Apache-2.0
  summary: Python bindings for the Selenium WebDriver for automating web browser interaction.
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
