{% set name = "selenium" %}
{% set version = "3.13.0" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: f35bb209cab740c195276a323c1b750dbcfdb9f6983e7d6e3abba9cd8838f355

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    
  run:
    - python

test:
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.android
    - selenium.webdriver.chrome
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.opera
    - selenium.webdriver.phantomjs
    - selenium.webdriver.remote
    - selenium.webdriver.support

about:
  home: http://www.seleniumhq.org/
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Python bindings for the Selenium WebDriver for automating web browser interaction.'
  dev_url: https://github.com/SeleniumHQ/selenium/
  doc_url: http://www.seleniumhq.org/docs/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
