{% set version = "4.22.0" %}

package:
  name: selenium
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
    sha256: 903c8c9d61b3eea6fcc9809dc7d9377e04e2ac87709876542cc8f863e482c4ce
  - fn: LICENSE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/LICENSE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/LICENSE
    sha256: de658a7d3761e92b471e2f630ea99eeb3389b27820809b1e4853baabd5fbadb7
  - fn: NOTICE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/NOTICE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/NOTICE
    sha256: 2a3429f61e1ad70d33a6fa517cb46ec183c0b0fbcce34a2183d4c56bea3c874e

build:
  noarch: python
  number: 2
  script:
    # 1. The first command removes the precompiled selenium-manager binaries.
    # (We depend on the conda-forge version instead.)
    # 2. The second command is optional and appends some Python code to
    # selenium/webdriver/common/__init__.py that warns when the SE_MANAGER_PATH
    # envvar is unset. (This helps diagnose issues where the selenium-manager
    # binary cannot be not found because the environment is not activated.)
    - |-
      {{ PYTHON }} -c "c = __import__('pathlib').Path('selenium/webdriver/common'); [(print(b), b.unlink()) for b in c.glob('*/selenium-manager*')]"
    - |-
      {{ PYTHON }} -c "i = __import__('pathlib').Path('selenium/webdriver/common/__init__.py'); i.write_text(i.read_text() + '''\n\n# Added by github.com/conda-forge/selenium-feedstock\nimport os; import sys; print('WARNING: The SE_MANAGER_PATH environment variable must be set to the location of the Selenium Manager binary. This should have been done by the selenium-manager_activate script in your Conda environment\\\\'s $CONDA_PREFIX/etc/conda/activate.d/ directory. The most likely reason for seeing this warning is that your Conda environment has not been properly activated. Please activate your Conda environment and try again. Alternatively, you can set the SE_MANAGER_PATH environment variable manually. Its expected location is $CONDA_PREFIX/bin/selenium-manager', file=sys.stderr) if 'SE_MANAGER_PATH' not in os.environ else None\n''')"
    - |
      {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - certifi >=2021.10.8
    - python >=3.8
    - selenium-manager {{ version.split('.')[:2] | join('.') }}.*
    # upstream trio* below are ~ operators with one trailing decimal
    - trio >=0.17,<1
    - trio-websocket >=0.9,<1
    - typing_extensions >=4.9,<5
    - urllib3 >=1.26,<3
    - websocket-client >=1.8.0
test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver.common
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check
    - python -c "from selenium.webdriver.common.selenium_manager import SeleniumManager; assert SeleniumManager._get_binary().exists()"
    # Ensure that the warning message is printed when the environment is not activated
    - unset SE_MANAGER_PATH
    - python -c "from selenium.webdriver.common.selenium_manager import SeleniumManager; assert SeleniumManager._get_binary().exists()" 2> out.txt || true
    - grep "your Conda environment has not been properly activated" out.txt

about:
  home: https://www.selenium.dev
  license_file:
    - LICENSE-selenium-{{ version }}
    - NOTICE-selenium-{{ version }}
  license: Apache-2.0
  summary: Official Python bindings for Selenium WebDriver
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
