{% set version = "4.17.0" %}

package:
  name: selenium
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
    sha256: 59d976b697df37e11d757df1e6798f1467ec1981456ca7ff9a98494f508f6eba
  - fn: LICENSE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/LICENSE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/LICENSE
    sha256: de658a7d3761e92b471e2f630ea99eeb3389b27820809b1e4853baabd5fbadb7
  - fn: NOTICE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/NOTICE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/NOTICE
    sha256: 2a3429f61e1ad70d33a6fa517cb46ec183c0b0fbcce34a2183d4c56bea3c874e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - certifi >=2021.10.8
    - python >=3.8
    - selenium-manager {{ version.split('.')[:2] | join('.') }}.*
    # upstream trio* below are ~ operators with one trailing decimal
    - trio >=0.17,<1
    - trio-websocket >=0.9,<1
    - urllib3 >=1.26,<3
test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check
    - python -c "from selenium.webdriver.common.selenium_manager import SeleniumManager; assert SeleniumManager.get_binary().exists()"

about:
  home: https://www.selenium.dev
  license_file:
    - LICENSE-selenium-{{ version }}
    - NOTICE-selenium-{{ version }}
  license: Apache-2.0
  summary: Python bindings for the Selenium WebDriver for automating web browser interaction.
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
