{% set version = "4.11.1" %}

package:
  name: selenium
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
    sha256: c16b95f6280d92b92ebe83ba4cbe75cbb07b6c5abf1680bf60158fb9209076ee
  - fn: LICENSE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/LICENSE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/LICENSE
    sha256: 5e1dea875e2c2a1707eb69ca64eee1faf6a8f2df818230943d590f794d12a359
  - fn: NOTICE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/NOTICE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/NOTICE
    sha256: 3e4b6f37b254d80f77ed41946e6f9ddd94ad4815b4578d207a6168fde6c68ad2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trio >=0.17,<1.dev0
    - trio-websocket >=0.9,<1.dev0
    - urllib3 >=1.26,<3
    - certifi >=2021.10.8
test:
  requires:
    - pip
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check

about:
  home: https://www.selenium.dev
  license_file:
    - LICENSE-selenium-{{ version }}
    - NOTICE-selenium-{{ version }}
  license: Apache-2.0
  summary: Python bindings for the Selenium WebDriver for automating web browser interaction.
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
