{%set version = "3.0.1"%}

package:
  name: selenium
  version: {{ version }}

source:
  fn: selenium-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
  sha256: 783e0064a34a026b924d0a1679d5b2ec633462e5091dd71ebd6e6d078674c597

build:

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.android
    - selenium.webdriver.chrome
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.opera
    - selenium.webdriver.phantomjs
    - selenium.webdriver.remote
    - selenium.webdriver.support

about:
  home: https://github.com/SeleniumHQ/selenium/
  license: Apache Software License Version 2.0
  summary: 'Python bindings for the Selenium WebDriver for automating web browser interaction.'

extra:
  recipe-maintainers:
    - pmlandwehr
