{% set version = "4.27.1" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: selenium
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/s/selenium/selenium-{{ version }}.tar.gz
    sha256: 5296c425a75ff1b44d0d5199042b36a6d1ef76c04fb775b97b40be739a9caae2
    patches:
      - 0000-no-rust.patch
  - fn: LICENSE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/LICENSE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/LICENSE
    sha256: de658a7d3761e92b471e2f630ea99eeb3389b27820809b1e4853baabd5fbadb7
  - fn: NOTICE-selenium-{{ version }}
    url:
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}-python/NOTICE
      - https://raw.githubusercontent.com/SeleniumHQ/selenium/selenium-{{ version }}/NOTICE
    sha256: 2a3429f61e1ad70d33a6fa517cb46ec183c0b0fbcce34a2183d4c56bea3c874e

build:
  noarch: python
  number: 1
  script:
    # ensure all static assets are included
    - echo "recursive-include * *.js" >> MANIFEST.in
    - echo "recursive-include * *.json" >> MANIFEST.in
    # ensure all directories have `__init__.py`
    - {{ PYTHON }} -c "from pathlib import Path; [(p / '__init__.py').touch() for p in Path('selenium').rglob('*') if p.is_dir()]"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - certifi >=2021.10.8
    - python >={{ python_min }}
    - selenium-manager {{ version.split('.')[:2] | join('.') }}.*
    - trio >=0.17,<1.0
    - trio-websocket >=0.9,<1.0
    - typing_extensions >=4.9,<5.0
    - urllib3 >=1.26,<3
    - websocket-client >=1.8,<2.0
test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver.common
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.remote
    - selenium.webdriver.support
  commands:
    - pip check

about:
  home: https://www.selenium.dev
  license_file:
    - LICENSE-selenium-{{ version }}
    - NOTICE-selenium-{{ version }}
  license: Apache-2.0
  summary: Official Python bindings for Selenium WebDriver
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
