# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.36.0"
  selenium_manager_version: ${{ (version | split('.'))[:2] | join('.') }}.*

package:
  name: selenium
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/selenium/selenium-${{ version }}.tar.gz
    sha256: 0eced83038736c3a013b824116df0b6dbb83e93721545f51b680451013416723
    patches:
      - 0000-no-rust.patch

build:
  number: 0
  noarch: python
  script:
    # ensure all static assets are included
    - echo "recursive-include * *.js" >> MANIFEST.in
    - echo "recursive-include * *.json" >> MANIFEST.in
    # ensure all directories have `__init__.py`
    - ${{ PYTHON }} -c "from pathlib import Path; [(p / '__init__.py').touch() for p in Path('selenium').rglob('*') if p.is_dir()]"
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - certifi >=2025.6.15
    - python >=${{ python_min }}
    - selenium-manager ${{ selenium_manager_version }}
    - trio >=0.30.0,<1.0
    - trio-websocket >=0.12.2,<1.0
    - typing_extensions >=4.14.0,<5.0
    - urllib3 >=2.5.0,<4.0
    - websocket-client >=1.8.0,<2.0

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
      imports:
        - selenium
        - selenium.common
        - selenium.webdriver.common
        - selenium.webdriver.chrome
        - selenium.webdriver.chromium
        - selenium.webdriver.edge
        - selenium.webdriver.firefox
        - selenium.webdriver.remote
        - selenium.webdriver.support
  - files:
      recipe: run_test.py
    requirements:
      run:
        - python ${{ python_min }}.*
    script:
      file: run_test.py
      interpreter: python

about:
  license_file:
    - LICENSE
    - NOTICE
  license: Apache-2.0
  summary: Official Python bindings for Selenium WebDriver
  homepage: https://www.selenium.dev
  repository: https://github.com/SeleniumHQ/selenium
  documentation: https://www.selenium.dev/documentation/webdriver

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - bollwyvl
